name: CIPipeline2

on:
 workflow_dispatch:
 schedule:
    - cron: '*/2 * * * *'

env:
  IMAGE_NAME: ginger-garlic
  GHCR_ROOT: ghcr.io
  GHCR: ghcr.io/kondetiramya

jobs:
  call-workflow:
    uses: ./.github/workflows/ci.yml
    with:
        client_password: "some value"
        environment: "dev"
        
