name: CI Pipeline

on:
  pull_request:
    branches: [ main ]
  issue_comment:
    types: [created]
env:
  IMAGE_NAME: ginger-garlic
  GHCR_ROOT: ghcr.io
  GHCR: ghcr.io/kondetiramya

jobs:
  build:

    runs-on: ubuntu-latest
    steps: 
    - name: skip ci
      if: ${{ contains(github.event.head_commit.message, 'ci skip') }}
      run: |
        echo "Run is being skipped"
        exit 1
    
    - name: Run PR
      if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/ci') }}
      run: |
        echo "Running the PR"
        exit 0
        
    - name: checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
