name: CI Pipeline

on:
  pull_request:
    branches: [ main ]
  issue_comment:
    types: [created]
env:
  IMAGE_NAME: ginger-garlic
  GHCR_ROOT: ghcr.io
  GHCR: ghcr.io/kondetiramya

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:     
    - name: checkout code
      uses: actions/checkout@v2
      with:
       fetch-depth: 0
         
    - name: skip ci
      env: 
        COMMIT_FILTER: "skip-ci"
      run: |
        # Get last commit message
        readonly local last_commit_log=$(git log -1 --pretty=format:"%s")
        echo "last commit log: $last_commit_log"

        readonly local filter_count=$(echo "$last_commit_log" | grep -c "$COMMIT_FILTER" )
        echo "number of occurence of '$COMMIT_FILTER' in '$last_commit_log': $filter_count"

        if [[ "$filter_count" -eq 0 ]]; then
          echo "all good, continue"
        else
          echo "the last commit log \"$last_commit_log\" contains \"$COMMIT_FILTER\", stopping"
          exit 78
        fi    
        
    - name: Run PR
      if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/ci') }}
      run: |
        echo "Running the PR"
        exit 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
