name: deploy workflow
on:
  workflow_call:
    inputs:
        environment:
            required: true
            type: string
        output1:
            required: false
            type: string
        concurrency:
            required: true
            type: boolean
    secrets:
        repo_access_token:
            required: true

env:
  IMAGE_NAME: ginger-garlic
  GHCR_ROOT: ghcr.io
  GHCR: ghcr.io/kondetiramya

jobs:
    deploy:
        environment: ${{inputs.environment}}
        runs-on: ubuntu-latest
        concurrency:
            group: "release-${{inputs.environment}}"
            cancel-in-progress: ${{inputs.concurrency}}
        steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        
        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 5.0.x
        
        - name: Restore dependencies
          run: dotnet restore
        
        - name: Build
          run: dotnet build --no-restore
        
        - name: Test
          run: dotnet test --no-build --verbosity normal
        
        - name: Install Gitversion
          uses: gittools/actions/gitversion/setup@v0.9.9
          with:
            versionSpec: '5.x'
        
        - name: Generate Version
          id: gitversion
          uses: gittools/actions/gitversion/execute@v0.9.9
          with:
            useConfigFile: true
            configFilePath: ./gitversion.yaml
            updateAssemblyInfo: true

        - name: Display outputs
          run: |
            echo ${{ inputs.output1 }}
