on:
  workflow_call:
    inputs:
        environment:
            required: true
            type: string
        output1:
            required: true
            type: string
        output2:
            required: true
            type: string
     secrets:
        repo_access_token:
            required: true
env:
  IMAGE_NAME: ginger-garlic
  GHCR_ROOT: ghcr.io
  GHCR: ghcr.io/kondetiramya
  
deploy:
    environment: $${{inputs.environment}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Install Gitversion
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
        versionSpec: '5.x'
    
    - name: Generate Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.9
      with:
        useConfigFile: true
        configFilePath: ./gitversion.yaml
        updateAssemblyInfo: true
    
    - uses: actions/checkout@v2
      with:
        repository: HylandSoftware/create-or-update-tag-action
        ref: v1
        token: ${{ secrets.repo_access_token }}
        path: ./.github/actions/create-or-update-tag

    - name: Tag the commit
      id: create-tag
      uses: ./.github/actions/create-or-update-tag
      with:
        token: ${{ secrets.repo_access_token }}
        tag-name: 'dev'
     
    - name: Print tag ref
      run: echo ${{ steps.create-tag.outputs.ref }}

    - name: Display outputs
      run: |
        echo ${{ inputs.output1 }}
        echo ${{ inputs.output2 }}