name: Run on main

on:
  push:
    branches: [ main ]
env:
  IMAGE_NAME: ginger-garlic
  GHCR_ROOT: ghcr.io
  GHCR: ghcr.io/kondetiramya
  OUTPUT: "some value"

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:         
    - name: checkout code
      uses: actions/checkout@v2
      with:
       fetch-depth: 0
       
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Set outputs
      id: step_output
      run: |
        echo "::set-output name=output1::This is output1"
  deploy-dev:
    needs: build
    uses: ./.github/workflows/deploy_template.yaml
    with:
        environment: Dev
        output1: ${{ env.OUTPUT }}
        concurrency: false
    secrets:
        repo_access_token: ${{ secrets.REPO_ACCESS_TOKEN }}
  
  deploy-staging:
    uses: ./.github/workflows/deploy_template.yaml
    with:
        environment: Staging
        concurrency: true
    secrets:
        repo_access_token: ${{ secrets.REPO_ACCESS_TOKEN }}
    needs:
    - build
    - deploy-dev
  
  deploy-prod:
    needs:
    - build
    - deploy-dev
    - deploy-staging
    uses: ./.github/workflows/deploy_template.yaml
    with:
        environment: Prod
        concurrency: true
    secrets:
        repo_access_token: ${{ secrets.REPO_ACCESS_TOKEN }}
